import type { Metadata } from "next";

import localFont from "next/font/local";
import Navbar from "@/components/Navbar";

const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff", // Path from 'dashboard' folder
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${geistMono.variable} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
